### ISSUE TITLE
Attribute name confusion between Readme and example

### ISSUE THREAD

**Issue by gyscos** [fitzgen/state_machine_future#1]
The example uses the attribute `#[state_machine_future(...)]` while the documentation following that uses `#[future_state_machine(...)]` - is this just a typo? Or am I missing something?

**Comment by gyscos** [comment]
Same thing with the derive attribute: `StateMachineFuture` vs `FutureStateMachine`

**Comment by fitzgen** [comment]
Typos -- good eye! Thanks for filing a bug. Will fix in a minute.

**Comment by fitzgen** [comment]
(and then copy-pasting typos...)

**Comment by fitzgen** [comment]
Fixed; thanks again!
