### ISSUE TITLE
Support for heterogeneous use of type parameters in states

### ISSUE THREAD

**Issue by randomPoison** [fitzgen/state_machine_future#2]
When using `#[derive(StateMachineFuture)]` on a type with a type parameter, I'm getting a compile error if any of the variants of my enum don't reference the type error. Here's a minimal version of what I'm running into:

```rust
#[derive(StateMachineFuture)]
enum SendState<T> {
    #[state_machine_future(start, transitions(Ready))]
    Sending {
        socket: UdpSocket
        buffer: T,
    },

    #[state_machine_future(ready)]
    Ready((UdpSocket, T)),

    #[state_machine_future(error)]
    Error(io::Error),
}

```

And here's the error I'm seeing:

```
error[E0392]: parameter `T` is never used
    --> src\lib.rs:1213:10
     |
1213 | #[derive(StateMachineFuture)]
     |          ^^^^^^^^^^^^^^^^^^ unused type parameter
     |
     = help: consider removing `T` or using a marker such as `std::marker::PhantomData`
```

I don't know if this is intended behavior or not, but it's certainly not ideal behavior from my perspective as a user. There are a few ways of working around it, such as using `PhantomData<T>` in the error case:

```
#[derive(StateMachineFuture)]
enum SendState<T> {
    ...

    #[state_machine_future(error)]
    Error((io::Error, PhantomData<T>)),
}
```

but doing so causes a lot of friction, at least in my case using tokio. It would be good if state_machine_future would allow some variants to not reference the type parameter, if possible. Also, if you know of a better workaround that I could use in the meantime, I'd appreciate it.

**Comment by fitzgen** [comment]
Thanks for filing an issue! This is the expected behavior, but I'm open to suggestions on how to end up with better ergonomics.

The most obvious way to do this (to me) is by traversing the whole `syn` AST and collectiong the set of type parameters used in each state, and then filtering the `where` clauses down to the ones that mention the used type parameters for each state. But that would probably be as much code as the whole rest of the crate...

https://github.com/fitzgen/state_machine_future/blob/master/tests/generics.rs#L1-L4

**Comment by fitzgen** [comment]
As far as workarounds, the only thing I know of is to use `map` and `map_err` to get rid of the `PhantomData` parts of the ready/error tuples.

**Comment by sfackler** [comment]
The easiest option on the implementation side could just be to allow the bounds to be overridden per-variant. serde has something similar:

```
#[derive(StateMachineFuture)]
enum SendState<T, U> {
    #[state_machine_future(error, bounds="U")]
    Foo(U),
}
```

**Comment by fitzgen** [comment]
Yeah, that's an OK compromise.

I'd merge a PR that added

* `#[state_machine_future(type_params(T, U, ...))]` using `darling::util::IdentList`, and
* `#[state_machine_future(where_clause("T: Default, U: Debug, ..."))]`

as attributes on state variants.

If either of you are interested in poking at this, I can help guide you around the code base.

**Comment by randomPoison** [comment]
@fitzgen The solution you originally described (i.e. traversing the AST to determine which type parameters are actually used by each variant) is what I would have suggested, though I'm sympathetic to concerns about it being complex to implement. Would you be open to a pull request that attempts the more complex solution? I can't make any promises that I'd be able to make it work, but I feel that it's the better solution as far as usability is concerned.

In the meantime, I'm working around the issue by using `map_err()` to add and remove the `PhantomData` as appropriate. It's not ideal, but this issue is at least not a major blocker.

Also, I want to say thanks for making this library! I was just yesterday talking to a friend about the troubles I was having writing state machines for futures, and this crate solved the problem beautifully. Thanks for putting together such a useful resource!

**Comment by fitzgen** [comment]
> Would you be open to a pull request that attempts the more complex solution?

Yes.

> I feel that it's the better solution as far as usability is concerned.

Agreed.

------------

I wish that https://github.com/fitzgen/scrapmetal worked on stable, it would make this so easy...

Anyways. I guess if I were to approach this problem, I would:

* Define an `Idents` trait to collect all the identifiers in some `syn` AST item, something like:

```rust
trait Idents {
    fn idents(&self, &mut HashSet<Ident>);
}
```

* Implement that trait for all the `syn` AST types.

* Implement a new `Phase` and `Pass` in `./derive_state_machine_future/src/phases.rs` that collects the used type parameters and their applicable `where` bounds leveraging that `Idents` trait.

**Comment by bkchr** [comment]
I have an implementation that works. It uses the complex solution. I will finish it (where clause still missing), clean it up and create a pull request :)
