### ISSUE TITLE
generate the machine and it's types into it's own module

### ISSUE THREAD

**Issue by swfsql** [fitzgen/state_machine_future#22]
Is it possible to generate the machine and it's types into it's own module?
This is because me and my colleague noticed that you can use another machine as a state in some other machine; then since the state's structure's names could collide/overlap, it would be really cool if one generated machine didn't necessarily interfered with some other one.

For a running example of this, you can see this https://www.grin-forum.org/t/peer-state-with-tokio/279

**Comment by bkchr** [comment]
Generating a state machine with into a specific module is not supported at the moment. However, you can place your state machines into modules own your own.

It may also be cleaner, to just create new files per state machine (when they are reasonable big). If not `mod statemachine1 { state_machine }` should work for you.

**Comment by swfsql** [comment]
Yes, creating a file for the machine solves it; thanks!

**Comment by fitzgen** [comment]
For posterity: `state_machine_future` actually used to emit its generated code in a new module, but trying to get imports for all the types that were used in each state correct was terribly difficult, so that approach was removed.
