### ISSUE TITLE
Possibility of using await!() ?

### ISSUE THREAD

**Issue by swfsql** [fitzgen/state_machine_future#23]
[I'm learning about futures], and it seems that the [await!()](https://github.com/alexcrichton/futures-await#technical-details) macro requires that the function doesn't use reference in parameters.
I guess that the usage of RentToOwn (which is a reference in the transition implementation's function signature) is a very basic/early assumption for this (state_machine_future) library. If it is not, is it possible to avoid the usage of a reference on the function signature?

Maybe this could be achieved if the state transitioned to itself, passing owned values to itself on each poll call; but if this were the case, I think there would be no possibility of multiple poll calling on the same state instance, because the state would transition to a new instance of the same state, with the same state internal variables.. so I think this wouldn't make sense.
or in other words: a NotReady would be a transition to a new instance of itself, which would be away from one of the future's "point", I suppose.

In any case, would you guys know if is there a viable chance of using await?
thanks in advance!

edit: perhaps.. the meaning of an "await!()" usage in this case would be an automatic generation of an inner state machine..?

**Comment by fitzgen** [comment]
I wouldn't recommend using `state_machine_future` with async/await and don't think it makes sense to emit async/await. This crate is essentially constructing control flow graphs as state machines, but with async/await you can express the control flow graph with normal control flow constructs. Async/await compiles down into state machines, essentially.

The references issue comes down to "self referential borrows". Check out things like `rental` and the new `Pin` RFC for immovable types for more details about that.

**Comment by swfsql** [comment]
Thanks fitzgen, I will study it
