### ISSUE TITLE
Broken build due to downstream dependency upgrade

### ISSUE THREAD

**Issue by thomaseizinger** [fitzgen/state_machine_future#35]
Currently, the build with Rust version 1.21 fails because there has been an upgrade to `lazy_static` that now uses const functions which is not yet available in Rust 1.21.
`lazy_static` itself promises to be compatible with Rust 1.24+.

The annoying thing is that it is only needed for install `cargo-readme` and not the actual build itself.

In order to keep the compatibility with Rust 1.21, we could install latest rust stable in the 1.21 branch just for installing `cargo-readme` and use Rust 1.21 to compile the actual project.

**Comment by hcpl** [comment]
Also, I don't see where `cargo-readme` is even called.

**Comment by thomaseizinger** [comment]
`cargo-readme` is called in an integration test to verify that README.md is up to date.

**Comment by hcpl** [comment]
Ah yeah, I forgot that this is possible :laughing:.

**Comment by thomaseizinger** [comment]
I am actually already working on a fix :)

**Comment by thomaseizinger** [comment]
Solved through #37.
