### ISSUE TITLE
Mandatory futures dependency

### ISSUE THREAD

**Issue by baloo** [fitzgen/state_machine_future#43]
When a crate using this lib tries to use `state_machine_future` without having a direct dependency on `futures` (using `tokio::prelude`), it yields an error like:
```
error[E0463]: can't find crate for `__smf_debuggable_futures`
```

I'm not experienced with derive implementation, but a better error like "direct futures dependency is mandatory" would help debug such use cases

**Comment by hcpl** [comment]
Or, even better, have a `#[doc(hidden)]` re-export of `futures::Future` and friends in `state_machine_future` and use those in `derive_state_machine_future`, like what many derive crates do (e.g. `serde` has [`export`](https://github.com/serde-rs/serde/blob/master/serde/src/lib.rs#L244-L246) and [`private`](https://github.com/serde-rs/serde/blob/master/serde/src/lib.rs#L248-L250) modules to exclusively support generated code).

**Comment by hcpl** [comment]
@baloo I've implemented the suggestion above in https://github.com/fitzgen/state_machine_future/pull/44. Please test it if you can!

**Comment by hcpl** [comment]
Resolved by https://github.com/fitzgen/state_machine_future/pull/44. cc @bkchr
