### ISSUE TITLE
non public structs used in state machines enum from the same module cause compilation error

### ISSUE THREAD

**Issue by alkis** [fitzgen/state_machine_future#6]
example:

```
struct State {
  x: u32,
}

#[derive(StateMachineFuture)]
enum MyStateMachine {
  #[state_machine_future(...
  Start(State),
  ...
}
```

**Comment by fitzgen** [comment]
Thanks for the bug report!

I guess removing the emitted module would fix this. I'll investigate.

**Comment by fitzgen** [comment]
Hmmm... it's pretty nice having that module though, since it gives us a place to add imports and attributes that apply to all the generated code. Will need to think a little more.
